FROM golang:1.18

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /usr/local/bin/ ./...

COPY frontend/ /usr/

EXPOSE 80
CMD ["api"]

# Github package requirement
# LABEL org.opencontainers.image.source https://github.com/princebillyGK/my-portfolio-backend

