FROM golang:1.18

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o ~/portfolio/cmd/bin/ ./...

RUN mv frontend ~/portfolio/frontend

EXPOSE 80
CMD ["~/.portfolio/cmd/bin/api"]

/* Github package requirement */
LABEL org.opencontainers.image.source https://github.com/princebillyGK/my-portfolio-backend

