FROM golang:1.18

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
ADD go.mod ./
RUN go mod download

ADD . .
RUN go build -v -o /usr/local/bin/ ./...

ADD frontend /usr/frontend

EXPOSE 80
CMD ["api"]-

# Github package requirement
# LABEL org.opencontainers.image.source https://github.com/princebillyGK/my-portfolio-backend

