on: [push]

name: AutoDeploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Login to Github container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and push to Github package
      uses: docker/build-push-action@v3
      with:
        context: .
        file: {context}/DontTouch.txt
        push: true
        tags: |
          portfolio-backend:latest
          portfolio-backend:${{ github.sha }}


    - name: Deploy to Web
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'princebillygk'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'ghcr.io/princebillygk/portfolio-backend:${{ github.sha }}'
