on: [push]

name: AutoDeploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: portfolio-backend
        tags: ${{ github.sha }}, latest
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
        dockerfile: Dockerfile

    - name: Deploy to Web
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'princebillygk'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'ghcr.io/princebillygk/portfolio-backend:${{ github.sha }}'
